title: GSA AI Community of Practice

# Custom CSS
sass:
  style: compressed # Ensures CSS is minified
  sass_dir: assets/css # Points to your CSS directory

# Include custom plugins if necessary
# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
