title: GSA AI Community of Practice

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme

# Custom CSS
sass:
  style: compressed # Ensures CSS is minified
  sass_dir: assets/css # Points to your CSS directory

# Include custom plugins if necessary
# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
